version: '3'

services:
  ali_manag:
    container_name: ali_manag
    build: .
    ports:
     - "80:80" 
    networks:
      vpcbr:
        ipv4_address: 10.5.0.9

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1